recipes/recipe/urls.py
from django.conf.urls import url

from . import views

app_name = 'recipe'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'submit/$', views.submit, name='submit'),
]

recipes/recipes/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^recipe/', include('recipe.urls')),
    url(r'^admin/', admin.site.urls),
]

recipes/recipe/models.py
from django.db import models
from mongoengine import *	

# Create your models here.
class Recipe(models.Model):
	name = StringField(max_length=200)
	ingredients = StringField()
	calories = IntField()
	prep_time = IntField()

	def __str__(self):
		return self.name

recipes/recipe/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.views import generic

from .models import Recipe

# Create your views here.
class IndexView(generic.ListView):
	template_name = 'recipe/index.html'
	context_object_name = 'recipe_list'

	def get_queryset(self):
		return Recipe.objects.order_by('name').order_by('calories')


def submit(request):
    if request.method == 'POST':
        rname = request.POST.get('name')
        ringredients = request.POST.get('ingredients')
        rcalories = request.POST.get('calories')
        rprep_time = request.POST.get('prep_time')
        recipe = Recipe.objects.create(name=rname, ingredients=ringredients, calories=rcalories, prep_time=rprep_time)
        try:
            recipe.save()
            return render(request, 'recipe/saved.html', None)
        except:
            return render(request, 'recipe/failed.html', None)
    else:
        return render(request, 'recipe/submit.html', None)

recipes/recipe/templates/recipe/failed.html
Could not add recipe.
<br />
<a href={% url 'recipe:index' %}>Home</a>

recipes/recipe/templates/recipe/index.html
{% if recipes %}
    <ul>
    {% for recipe in recipes %}
        <li>{{ recipe.name }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No recipes are available.</p>
{% endif %}
<br />
<a href=./submit>Submit a recipe</a>&nbsp;&nbsp;

recipes/recipe/templates/recipe/saved.html
The recipe has been added!
<br />
<a href={% url 'recipe:index' %}>Home</a>

recipes/recipe/templates/recipe/submit.html
<h1>Add Recipe</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'recipe:submit' %}" method="post">
{% csrf_token %}
    Name :        <input type="text" name="name" id="name"/><br>
    Ingredients : <input type="text" name="ingredients" id="ingredients" /><br>
    Calories :    <input type="text" name="calories" id="calories" /><br>
    Time needed (in minutes) : <input type="text" name="prep_time" id="prep_time" /><br>
 
<input type="submit" value="Submit" />
</form>